- build.gradle
- src/scratch/kevin/ucerf3/downDipSubSectTest/demo/SectionXml2Csv.java
Implements Feature: opensha crustal subsection geometry extraction utility #22
> added comandline tool to explore subsections

- build.gradle
- data/FaultModels/DEMO2_DIPFIX_crustal_opensha.xml
- src/main/java/nz/cri/gns/NSHM/opensha/demo/Demo01_Hikurangi.java
- src/main/java/nz/cri/gns/NSHM/opensha/demo/Demo02_HikurangiCrustal.java
- src/main/java/nz/cri/gns/NSHM/opensha/demo/Demo03_RupturesAndInversion.java
- src/main/java/nz/cri/gns/NSHM/opensha/demo/Demo04_RupSetDiagnostics.java
- src/main/java/nz/cri/gns/NSHM/opensha/ruptures/downDipSubSectTest/DownDipTestRupSetBuilder.java
- src/main/java/nz/cri/gns/NSHM/opensha/scripts/scriptCrustalInversionRunner.java
- src/main/java/scratch/kevin/ucerf3/StandaloneSubSectRupGenMG.java
- src/main/java/scratch/kevin/ucerf3/StandaloneSubSectRupGenNZCFM.java
- src/main/java/scratch/kevin/ucerf3/downDipSubSectTestOld/DownDipTestPlausibilityConfig.java
- test/java/NSHM_NZ/inversion/InterfaceRuptureSetBuilderTest.java
Take all Chris's testing work into Travis for CI build/test cycle
> 45 rupture set analysis

- build.gradle
- src/main/java/nz/cri/gns/NSHM/opensha/demo/Demo01_Hikurangi.java
- src/main/java/nz/cri/gns/NSHM/opensha/demo/Demo02_HikurangiCrustal.java
- src/main/java/nz/cri/gns/NSHM/opensha/demo/Demo03_RupturesAndInversion.java
- src/main/java/nz/cri/gns/NSHM/opensha/demo/SectionXml2Csv.java
- src/main/java/nz/cri/gns/NSHM/opensha/scripts/scriptCrustalInversionRunner.java
- src/main/java/nz/cri/gns/NSHM/opensha/util/FaultSectionList.java
- test/java/nz/cri/gns/NSHM/opensha/util/FaultSectionListTest.java
Data sanity checks #34
Turned out a little over-engineered, but this way we automatically keep track of what id is safe to use to generate the next set of subsections.
> data sanity checks #34

- src/python/automation/run_rupture_sets.py
Python script saving all results, inputs, metrics for a swathe of rupture build tests (currently ~300).
> refactored new run_rupture_sets.py; ready for real world!

- build.gradle
- src/integration/java/nz/cri/gns/NSHM/opensha/ruptures/NSHMRuptureSetBuilderIntegration.java
- src/integration/resources/KAIK2016.xml
- src/integration/resources/alpine-vernon.xml
- src/main/java/nz/cri/gns/NSHM/opensha/ruptures/NSHMRuptureSetBuilder.java
- src/main/java/nz/cri/gns/NSHM/opensha/ruptures/NSHMSlipEnabledRuptureSet.java
> [53] rupture generation integration test

- gradle/wrapper/gradle-wrapper.properties
- scripts/autom.pbs
- scripts/autom2.pbs
- scripts/autom3.pbs
- src/python/automation/run_rupture_sets.py
- revert gradle version to one that is compatible with beavan environment. Hopefully this survives everywhere else.
- minor fixes in python run script
- added 3 pbs scripts
> beavan changes

- src/main/java/nz/cri/gns/NSHM/opensha/ruptures/CoarseUCERF3ClusterPermutationStrategy.java
- test/java/nz/cri/gns/NSHM/opensha/ruptures/CoarseUCERF3ClusterPermutationStrategyTest.java
Implements #68. This is a platform for testing different approaches to rupture coarsening.
> [68] added coarse permutation strategy

- scripts/autom.pbs
- scripts/autom2.pbs
- scripts/autom3.pbs
- src/main/java/nz/cri/gns/NSHM/opensha/inversion/NSHMInversionRunner.java
- src/main/java/nz/cri/gns/NSHM/opensha/scripts/scriptCrustalInversionRunner.java
- src/main/java/nz/cri/gns/NSHM/opensha/util/NSHMPythonGateway.java
implements #42 apart from python wrapper
> [42] created NSHMInversionRunner

- src/integration/java/nz/cri/gns/NSHM/opensha/ruptures/NSHMRuptureSetBuilderIntegration.java
- src/main/java/nz/cri/gns/NSHM/opensha/ruptures/NSHMRuptureSetBuilder.java
- src/main/java/nz/cri/gns/NSHM/opensha/ruptures/downDipSubSectTest/DownDipTestPermutationStrategy.java
- src/main/java/nz/cri/gns/NSHM/opensha/scripts/scriptCrustalInversionRunner.java
- src/main/java/nz/cri/gns/NSHM/opensha/util/FaultSectionList.java
- src/main/java/nz/cri/gns/NSHM/opensha/util/NSHMPythonGateway.java
- test/java/nz/cri/gns/NSHM/opensha/ruptures/downDipSubSectTest/DownDipTestPermutationStrategyTest.java
> [71] added downdip coarsening

- src/main/java/nz/cri/gns/NSHM/opensha/ruptures/NSHMRuptureSetBuilder.java
- src/main/java/nz/cri/gns/NSHM/opensha/ruptures/downDipSubSectTest/DownDipTestPermutationStrategy.java
- test/java/nz/cri/gns/NSHM/opensha/ruptures/downDipSubSectTest/DownDipTestPermutationStrategyTest.java
> [#75] Elastic upper aspect ratio for building subduction ruptures

- src/main/java/nz/cri/gns/NSHM/opensha/hazard/NSHMHazardCalculator.java
- src/main/java/nz/cri/gns/NSHM/opensha/hazard/NSHMHazardCalculatorBuilder.java
- src/main/java/nz/cri/gns/NSHM/opensha/scripts/HazardCalculatorScript.java
- src/main/java/nz/cri/gns/NSHM/opensha/scripts/scriptCrustalInversionRunner.java
- src/main/java/nz/cri/gns/NSHM/opensha/util/NSHMPythonGateway.java
- src/python/automation/run_inversion_hazard.py
> [#82] hazard calculation

- src/main/java/nz/cri/gns/NSHM/opensha/ruptures/downDipSubSectTest/FaultIdFilter.java
- src/main/java/nz/cri/gns/NSHM/opensha/ruptures/downDipSubSectTest/RectangularityFilter.java
- test/java/nz/cri/gns/NSHM/opensha/ruptures/downDipSubSectTest/FaultIdFilterTest.java
fixes plausibility filters after UCERF3 upstream merge
> fixes after pulling upstream changes

- src/integration/java/nz/cri/gns/NSHM/opensha/ruptures/NSHMRuptureSetBuilderIntegration.java
- src/main/java/nz/cri/gns/NSHM/opensha/ruptures/NSHMRuptureSetBuilder.java
Fixes the disabled azimuth filters which our integration tests picked up :)
> restored azimuth plausibility, picked up in integration tests

- src/main/java/nz/cri/gns/NZSHM22/opensha/ruptures/NZSHM22_RuptureSetBuilder.java
> 123 file names

- src/main/java/nz/cri/gns/NZSHM22/opensha/ruptures/NZSHM22_RuptureSetBuilder.java
> fix thinningFactor

- src/integration/java/nz/cri/gns/NZSHM22/opensha/ruptures/NZSHM22_AzimuthalRuptureSetBuilder_IntegrationTest.java
- src/integration/java/nz/cri/gns/NZSHM22/opensha/ruptures/NZSHM22_CoulombRuptureSetBuilder_IntegrationTest.java
- src/main/java/nz/cri/gns/NZSHM22/opensha/ruptures/NZSHM22_AbstractRuptureSetBuilder.java
- src/main/java/nz/cri/gns/NZSHM22/opensha/ruptures/NZSHM22_AzimuthalRuptureSetBuilder.java
- src/main/java/nz/cri/gns/NZSHM22/opensha/ruptures/NZSHM22_CoulombRuptureSetBuilder.java
- src/main/java/nz/cri/gns/NZSHM22/opensha/scripts/scriptCrustalInversionRunner.java
- src/main/java/nz/cri/gns/NZSHM22/opensha/util/NZSHM22_PythonGateway.java
> added NZSHM22_CoulombRuptureSetBuilder

- src/main/java/nz/cri/gns/NZSHM22/opensha/enumTreeBranches/NZSHM22_FaultModels.java
- src/main/java/nz/cri/gns/NZSHM22/util/NZSHM22_FilteredInversionDiagnosticsReport.java
- src/main/resources/faultModels/cfm_0_9_d90_all.xml.FaultsByNameAlt.txt
- src/main/resources/faultModels/cfm_0_9_d90_no_tvz.xml.FaultsByNameAlt.txt
> added named faults to a couple of our models

- src/main/java/nz/cri/gns/NZSHM22/opensha/enumTreeBranches/NZSHM22_DeformationModels.java
- src/main/java/nz/cri/gns/NZSHM22/opensha/ruptures/NZSHM22_AbstractRuptureSetBuilder.java
> [#169] making it possible to force a global slip rate for all faults

- .github/workflows/gradle.yml
slightly modified default gradle yaml file
> setting up github action

- src/main/java/nz/cri/gns/NZSHM22/opensha/hazard/NZSHM22_HazardCalculatorBuilder.java
- src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_CrustalInversionRunner.java
- src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_InversionFaultSystemRuptSet.java
> [#172] set min mag

- src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_CrustalInversionRunner.java
- src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_SubductionInversionRunner.java
- src/main/java/nz/cri/gns/NZSHM22/opensha/ruptures/NZSHM22_AzimuthalRuptureSetBuilder.java
- src/main/java/nz/cri/gns/NZSHM22/opensha/ruptures/NZSHM22_CoulombRuptureSetBuilder.java
- src/main/java/nz/cri/gns/NZSHM22/opensha/ruptures/NZSHM22_SubductionRuptureSetBuilder.java
- src/main/java/nz/cri/gns/NZSHM22/opensha/util/NZSHM22_PythonGateway.java
> [#162] remove duplicate methods in subclasses
